### ISSUE TITLE
I have some questions about your approach

### ISSUE THREAD

**Issue by sitaocheng** [PhilippChr/wikidata-core-for-QA#2]
Hi, there. 
    Thank you for your code and it's clear and helpful. I'm trying to use it to process KB and have some questions.

- I'm trying to understand the filtering process. Have you compared the size of KB (predicates, entities, etc. ) before and after using your code? or how many predicates have your filtered out?  I notice that you just deleted ExternalID and GeoShape for predicates and filtered out some entities using rules. Is that because the ExternalID and GeoShape takes a large proportion?
-  Why resolving the qualifiers is helpful for question answering, I'm curious about some detailed effects of this step. I think maybe skipping this step is okay.
- Just my interest. As you know, images and videos need a lot of memory to store, but they don't exit in .ttl and .nt files (so for as i know). Do you know how these special types of KB information are stored .ttl or .nt files?

I appreciate it for your precious time.

**Comment by PhilippChr** [comment]
Hi, 

Thanks a lot for your interest in our work!

1) Resolving qualifiers does not change the data, but just the way it is stored
and probably retrieved. This can have an effect on the runtime when the dump
is indexed appropriately, e.g. as in this project, that makes use of the pruned dump:
https://clocq.mpi-inf.mpg.de/
"Beyond NED: Fast and Effective Search Space Reduction for Complex Question Answering over Knowledge Bases”,
Philipp Christmann, Rishiraj Saha Roy, and Gerhard Weikum,
WSDM 2022.

2) We pruned several facts that are mostly not required for QA tasks.
So what we prune are non-Wikidata facts, e.g. linkings to other KBs,
DBs or similar. Further, entity and predicate labels are pruned from
the dump, and the English labels maintained in a dedicated dictionary 
instead. Finally, the externalIDs are removed. They may consume quite
some space, but can also confuse downstream QA systems. The names
of such external predicates often have a semantically relevant surface
form, except for the “ID”. 

Further, there may well be other triples in the dump that are irrelevant
for most QA cases. For example, there is a lot of detailed information
on chemical elements, or research papers.
Therefore, I am pretty sure that further pruning is possible.

At some point we computed statistics of how many triples are pruned.
If I remember correctly, with a 2021 Wikidata dump, the size was reduced
from 12 billion to 2 billion **triples**, via the pruning.
To obtain the same statistics for newer dumps, one could count the lines
of the input and output files.

3) I do not have any experience with these kinds of information.
One could potentially encode the image-data and keep it in the .ttl or .nt
file. However, I feel that maintaining a link (either internal file path or web
link) would be a cleaner solution.

Good luck with your project!

Regards,
Philipp
